services:
  mongo:
    image: mongo:7
    container_name: app_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: app
    volumes:
      - mongo_data:/data/db
    networks:
      - app_net

  redis:
    image: redis:7-alpine
    container_name: app_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - app_net

volumes:
  mongo_data:
  redis_data:

networks:
  app_net:
    driver: bridge
