"use client";

import { Activity, Coins, ShoppingBag, Target } from "lucide-react";
import { useMemo } from "react";
import {
	Area,
	AreaChart,
	CartesianGrid,
	ResponsiveContainer,
	Tooltip,
	XAxis,
	YAxis,
} from "recharts";

import { LoadingTableSkeleton } from "@/components/common/loading-table-skeleton";
import { Badge } from "@/components/ui/badge";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "@/components/ui/card";
import { useMockLoading } from "@/hooks/use-mock-loading";
import { formatCurrency } from "@/lib/formatters";
import { orders } from "@/mocks/orders";
import { payments } from "@/mocks/payments";
import { raffles } from "@/mocks/raffles";

type ChartPoint = {
	label: string;
	revenue: number;
};

function buildChartData(): ChartPoint[] {
	const paidPayments = payments.filter((payment) => payment.status === "paid");

	if (paidPayments.length === 0) {
		return [];
	}

	const timestamps = paidPayments.map((item) =>
		new Date(item.processedAt).getTime(),
	);
	const maxTimestamp = Math.max(...timestamps);
	const oneDayInMs = 86_400_000;

	return Array.from({ length: 7 }).map((_, index) => {
		const currentTime = maxTimestamp - (6 - index) * oneDayInMs;
		const currentDate = new Date(currentTime);
		const dayKey = currentDate.toISOString().slice(0, 10);

		const revenue = paidPayments
			.filter((payment) => payment.processedAt.startsWith(dayKey))
			.reduce((acc, item) => acc + item.amount, 0);

		return {
			label: new Intl.DateTimeFormat("pt-BR", {
				day: "2-digit",
				month: "2-digit",
			}).format(currentDate),
			revenue,
		};
	});
}

export function DashboardView() {
	const isLoading = useMockLoading();

	const stats = useMemo(() => {
		const paidRevenue = payments
			.filter((payment) => payment.status === "paid")
			.reduce((acc, item) => acc + item.amount, 0);

		const pendingOrders = orders.filter(
			(order) => order.status === "pending",
		).length;
		const activeRaffles = raffles.filter(
			(raffle) => raffle.status === "active",
		).length;

		const soldTickets = raffles.reduce(
			(acc, raffle) => acc + raffle.soldTickets,
			0,
		);
		const totalTickets = raffles.reduce(
			(acc, raffle) => acc + raffle.totalTickets,
			0,
		);
		const occupancy = totalTickets > 0 ? (soldTickets / totalTickets) * 100 : 0;

		return {
			paidRevenue,
			pendingOrders,
			activeRaffles,
			occupancy,
		};
	}, []);

	const chartData = useMemo(buildChartData, []);

	const topRaffles = useMemo(() => {
		return [...raffles]
			.sort(
				(a, b) =>
					b.soldTickets / b.totalTickets - a.soldTickets / a.totalTickets,
			)
			.slice(0, 4);
	}, []);

	if (isLoading) {
		return <LoadingTableSkeleton rows={8} />;
	}

	return (
		<section className="space-y-5">
			<header className="space-y-2">
				<p className="font-mono text-xs uppercase tracking-[0.15em] text-primary">
					Operational command center
				</p>
				<h2 className="text-2xl font-semibold uppercase tracking-[0.04em]">
					Performance Snapshot
				</h2>
			</header>

			<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
				<Card>
					<CardHeader className="pb-2">
						<CardDescription className="flex items-center gap-2 uppercase tracking-[0.08em]">
							<Coins className="size-4 text-primary" />
							Net Revenue
						</CardDescription>
						<CardTitle>{formatCurrency(stats.paidRevenue)}</CardTitle>
					</CardHeader>
				</Card>

				<Card>
					<CardHeader className="pb-2">
						<CardDescription className="flex items-center gap-2 uppercase tracking-[0.08em]">
							<ShoppingBag className="size-4 text-primary" />
							Pending Orders
						</CardDescription>
						<CardTitle>{stats.pendingOrders}</CardTitle>
					</CardHeader>
				</Card>

				<Card>
					<CardHeader className="pb-2">
						<CardDescription className="flex items-center gap-2 uppercase tracking-[0.08em]">
							<Activity className="size-4 text-primary" />
							Active Raffles
						</CardDescription>
						<CardTitle>{stats.activeRaffles}</CardTitle>
					</CardHeader>
				</Card>

				<Card>
					<CardHeader className="pb-2">
						<CardDescription className="flex items-center gap-2 uppercase tracking-[0.08em]">
							<Target className="size-4 text-primary" />
							Ticket Occupancy
						</CardDescription>
						<CardTitle>{stats.occupancy.toFixed(1)}%</CardTitle>
					</CardHeader>
				</Card>
			</div>

			<div className="grid gap-4 xl:grid-cols-[1.4fr_1fr]">
				<Card>
					<CardHeader>
						<CardTitle className="uppercase tracking-[0.04em]">
							Sales Pulse (7 days)
						</CardTitle>
						<CardDescription>
							Revenue generated by paid payments.
						</CardDescription>
					</CardHeader>
					<CardContent className="h-72">
						<ResponsiveContainer width="100%" height="100%">
							<AreaChart data={chartData}>
								<defs>
									<linearGradient
										id="revenueGradient"
										x1="0"
										y1="0"
										x2="0"
										y2="1"
									>
										<stop
											offset="5%"
											stopColor="var(--color-chart-1)"
											stopOpacity={0.6}
										/>
										<stop
											offset="95%"
											stopColor="var(--color-chart-1)"
											stopOpacity={0.02}
										/>
									</linearGradient>
								</defs>
								<CartesianGrid
									strokeDasharray="4 4"
									stroke="var(--border)"
									vertical={false}
								/>
								<XAxis
									dataKey="label"
									stroke="var(--muted-foreground)"
									tickLine={false}
									axisLine={false}
								/>
								<YAxis
									stroke="var(--muted-foreground)"
									tickLine={false}
									axisLine={false}
									tickFormatter={(value) => `R$ ${value}`}
								/>
								<Tooltip
									contentStyle={{
										background: "var(--card)",
										border: "1px solid var(--border)",
										borderRadius: 12,
									}}
									formatter={(value: number | string | undefined) => [
										formatCurrency(
											typeof value === "number" ? value : Number(value ?? 0),
										),
										"Revenue",
									]}
								/>
								<Area
									type="monotone"
									dataKey="revenue"
									stroke="var(--color-chart-1)"
									fill="url(#revenueGradient)"
									strokeWidth={2}
								/>
							</AreaChart>
						</ResponsiveContainer>
					</CardContent>
				</Card>

				<Card>
					<CardHeader>
						<CardTitle className="uppercase tracking-[0.04em]">
							Top Selling Raffles
						</CardTitle>
						<CardDescription>Highest ticket occupancy rate.</CardDescription>
					</CardHeader>
					<CardContent className="space-y-3">
						{topRaffles.map((raffle) => {
							const ratio = (raffle.soldTickets / raffle.totalTickets) * 100;

							return (
								<article
									key={raffle.id}
									className="rounded-md border border-border/70 bg-background/40 p-3"
								>
									<div className="mb-1.5 flex items-start justify-between gap-2">
										<p className="text-sm font-medium">{raffle.title}</p>
										<Badge className="border-primary/40 bg-primary/10 text-primary">
											{ratio.toFixed(1)}%
										</Badge>
									</div>
									<p className="text-xs text-muted-foreground">
										{raffle.soldTickets} / {raffle.totalTickets} tickets sold
									</p>
								</article>
							);
						})}
					</CardContent>
				</Card>
			</div>
		</section>
	);
}
